name: Hourly Beach Status Check

on:
  # Run this workflow on a schedule (at the top of every hour)
  schedule:
    - cron: '0 * * * *'
  # Allow running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check-and-notify:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code so we can access our files
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 3: Install our Python libraries
      - name: Install dependencies
        run: pip install requests pdfplumber

      # Step 4: Run our Python script to check for changes
      - name: Run status checker script
        run: python check_status.py

      # Step 5: Commit and push the status file if it has changed
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add current_status.txt
          # The following command will fail if there are no changes, which is fine.
          # We use `|| true` to prevent the workflow from failing on this expected behavior.
          git commit -m "Update beach status" || true
          git push
