# .github/workflows/deploy.yml

name: Deploy Frontend and Backend

on:
  push:
    branches:
      - main # This action runs only when you push to the main branch

jobs:
  # --- JOB 1: DEPLOY THE BACKEND WORKER ---
  deploy-backend:
    runs-on: ubuntu-latest
    name: Deploy Backend to Cloudflare
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install Wrangler
        run: npm install -g wrangler
        
      - name: Deploy to Cloudflare Workers
        run: wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

  # --- JOB 2: DEPLOY THE FRONTEND TO GITHUB PAGES ---
  deploy-frontend:
    runs-on: ubuntu-latest
    name: Deploy Frontend to GitHub Pages
    permissions:
      contents: write # This gives the job permission to write to the repository
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # A standard version

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # This tells the action to take the contents of your 'frontend' folder...
          publish_dir: ./frontend
          # ...and push them to the 'gh-pages' branch.
          publish_branch: gh-pages
